<?php
/**
 * Plugin Name: WP Rocket | Modify the Used CSS
 * Description: Allows various modifications to the contents of the Used CSS generated by Remove Unused CSS
 * Author:      WP Rocket Support Team
 * Author URI:  http://wp-rocket.me/
 * License:     GNU General Public License v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Copyright SAS WP MEDIA 2024
 */

namespace WP_Rocket\Helpers\rucss\rucss_modify_used_css;

// Standard plugin security, keep this line in place.
defined( 'ABSPATH' ) or die();


function get_configs() {

  $configs = [

    'rocket_rucss_external_exclusions' => [
      // '/wp-content/plugins/plugin-name/css/file.css'
    ],

    'rocket_rucss_inline_content_exclusions' => [
      /**
       * EDIT THIS:
       * Edit below line as needed to exclude files.
       * Copy the entire line into a new line for each style declaration you want you exclude.
       */
      // '.targetSelector',
    ],

    'rocket_rucss_inline_atts_exclusions' => [
      '',
    ],

    'rocket_rucss_skip_styles_with_attr' => [
      '',
    ],

    'prepend_css' => [
      '',
    ],

    'append_css' => [
      '',
    ],

    'filter_css' => [
      'css_removed' => '',
      'css_inserted' => '',
    ],
  ];

  return $configs;
}


/**
 * Exclude inline styles from being removed by WP Rocket’s Remove Unused CSS optimization.
 */
function inline_exclusions( $inline_exclusions = array() ) {

  $configs = get_configs();

  foreach ( $configs['rocket_rucss_inline_atts_exclusions'] as $rocket_rucss_inline_atts_exclusion ) {
	  $inline_exclusions[] = $rocket_rucss_inline_atts_exclusion;
  }

	return $inline_exclusions;
}
add_filter( 'rocket_rucss_inline_content_exclusions', __NAMESPACE__ . '\inline_exclusions' );

