<?php
/**
 * Plugin Name: WP Rocket | Fix encoded characters in the Used CSS
 * Description: Allows filtering the contents of the Used CSS generated by Remove Unused CSS
 * Author:      WP Rocket Support Team
 * Author URI:  http://wp-rocket.me/
 * License:     GNU General Public License v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Copyright SAS WP MEDIA 2024
 */

namespace WP_Rocket\Helpers\static_files\optimizations\rucss_fix_encoding_used_css;

// Standard plugin security, keep this line in place.
defined('ABSPATH') or die();

/**
 * Filter the used CSS generated by WP Rocket’s Remove Unused CSS optimization.
 */
function filter_css($css)
{

    /**
     * EDIT THIS:
     * Edit below line as needed to add replacements, you can change or remove lines as needed.
     * To replace multiple inline css declarations, copy the entire line into a new line for each style declaration you want you replace.
     */

    $css = str_replace('%20', ' ', $css);
    $css = str_replace('%7B', '{', $css);
    $css = str_replace('%7D', '}', $css);
    $css = str_replace('%3E', '>', $css);
    $css = str_replace('%3c', '>', $css);
    $css = str_replace(' ', ' ', $css);


    // STOP EDITING
    return $css;
}
add_filter('rocket_usedcss_content', __NAMESPACE__ . '\rucss_fix_encoding_used_css');
