<?php
/**
 * Plugin Name: WP Rocket | Filter the content of the Used CSS
 * Description: Allows filtering the contents of the Used CSS generated by Remove Unused CSS
 * Author:      WP Rocket Support Team
 * Author URI:  http://wp-rocket.me/
 * License:     GNU General Public License v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Copyright SAS WP MEDIA 2022
 */

namespace WP_Rocket\Helpers\static_files\optimizations\rucss_filter_used_css;

// Standard plugin security, keep this line in place.
defined( 'ABSPATH' ) or die();

/**
 * Filter the used CSS generated by WP Rocket’s Remove Unused CSS optimization.
 */
function filter_css( $css ) {

    /**
     * EDIT THIS:
     */

    /*
     * Search and replace values
     * Edit line 34 str_replace() function.
     * Change `old` to the value to replace. Change `new` with the replacement value.
     * To replace multiple inline css declarations, copy the entire line into a new line for each style declaration you want you replace.
     */

    // $css = str_replace( 'old', 'new', $css);

    /**
     * Prepend CSS to the Used CSS
     * Replace line 41's value with the desired style to prepend.
     */

    // $prependedss = '.new_css {background: red;}';
    // $css = $prependedcss . $css;

    /**
     * Append CSS to the Used CSS
     * Replace line 49's value with the desired style to append.
     */

    // $appendedcss = '.new_css {background: red;}';
    // $css = $css . $appendedcss;

    // STOP EDITING
    
    return $css;
    
}
add_filter( 'rocket_usedcss_content', __NAMESPACE__ . '\filter_css' );