<?php
/**
 * Plugin Name: WP Rocket | Custom Cache Folders
 * Description: Use custom folder for WP Rocket cache files. 
 * Plugin URI:  https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-custom-folders
 * Author:      WP Rocket Support Team
 * Author URI:  http://wp-rocket.me/
 * License:     GNU General Public License v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.html
 *
 * Copyright SAS WP MEDIA 2018
 */

namespace WP_Rocket\Helpers\wp_rocket_custom_cache_folders;

// Standard plugin security, keep this line in place.
defined( 'ABSPATH' ) or die();

// EDIT HERE:

// Specify your custom cache folder. Do not forget the trailing slash. 
if ( ! defined( 'WP_ROCKET_CACHE_ROOT_PATH' ) ) {
	define( 'WP_ROCKET_CACHE_ROOT_PATH', WP_CONTENT_DIR . '/your-wp-rocket-cache-folder/' );
}

// Specify the URL to the custom cache folder. 
if ( ! defined( 'WP_ROCKET_CACHE_ROOT_URL' ) ) {
	define( 'WP_ROCKET_CACHE_ROOT_URL', 'http://your-domain.com/wp-content/your-wp-rocket-cache-folder/' );
}

// Specify the path to the custom folder where WP Rocket will create it's config file. 
if ( ! defined( 'WP_ROCKET_CONFIG_PATH' ) ) {
	define( 'WP_ROCKET_CONFIG_PATH', WP_CONTENT_DIR.'/your-wp-rocket-config-folder/' ); 
}

// STOP EDITING

/**
 * Filter the contents of advanced-cache.php to reflect new folders
 * 
 * @param (string) $buffer Contents of the advanced-cache.php as generated by the get_rocket_advanced_cache_file() WP Rocket function. 
 * 
 * @author Arun Basil Lal
 */
function modify_advanced_cache_file( $buffer ) {
	
	$prefix  = "\n\n";
	$prefix .= "define( 'WP_ROCKET_CACHE_ROOT_PATH'	, '" . WP_ROCKET_CACHE_ROOT_PATH . "' );\n";
	$prefix .= "define( 'WP_ROCKET_CACHE_ROOT_URL'	, '" . WP_ROCKET_CACHE_ROOT_URL . "' );\n";
	$prefix .= "define( 'WP_ROCKET_CONFIG_PATH'	, '" . WP_ROCKET_CONFIG_PATH . "' );";
	
	$buffer  = preg_replace( "/defined\( 'ABSPATH' \) \|\| exit;/", '$0' . $prefix, $buffer, 1 );
	
	return $buffer;
}
add_filter( 'rocket_advanced_cache_file', __NAMESPACE__ . '\modify_advanced_cache_file' );